# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# DataSource (AWS RDS)
spring.datasource.url=jdbc:postgresql://database-2.cpuy0aoie7ni.eu-north-1.rds.amazonaws.com:5432/Curd_db
spring.datasource.username=postgres
spring.datasource.password=Narzo60123
spring.datasource.driver-class-name=org.postgresql.Driver